### PR TITLE
fix: do not remove trailing slashes during registration

### LINKED ISSUE #38: Removal of trailing slashes during registration is not always valid
During the registration, we remove trailing slashes. This could make sense if you want to make an API call and create the endpoint with something like this: `$shopUrl . ' /api/...` 
This would work for shops like `my-shop.com` and also for `my-shop.com/` if you are removing the trailing slash from the URL itself. 
As it is valid to have `my-shop.com/staging/`, removing the trailing slash should not happen. 
Using for example the guzzle client, it is possible to set the `base_uri` which can include the trailing slash. If the route is `/api/...`, it would not result in double slashes as guzzle already takes care of this. The documentation can be found here: https://docs.guzzlephp.org/en/stable/quickstart.html#creating-a-client

### PR DESCRIPTION
**Pull request by MoritzKrafeld**
Fixes #38 
With that change, it is now possible to properly register shops with URL's like `my-shop.com/staging/` without removing the trailing slash.

### CODE REVIEW

File: src/Registration/RegistrationService.php [hunk 1]
```diff
@@ -156,7 +156,6 @@ private function sanitizeShopUrl(string $shopUrl): string
 
         /** @var string $normalizedPath */
         $normalizedPath = preg_replace('#/{2,}#', '/', $path);
-        $normalizedPath = rtrim($normalizedPath, '/');
```
Comment (nsaliu) [inline src/Registration/RegistrationService.php:159]: Fine with it 👍  but can we not just simply remove the entire method?

Comment (MoritzKrafeld) [reply src/Registration/RegistrationService.php:159]: I would also be fine with that so that we just use the URL which we are getting from the shop without making any adjustments to that :smile:

Comment (SebastianFranze) [reply src/Registration/RegistrationService.php:159]: At least you can shorten it a bit:

```php
private function sanitizeShopUrl(string $shopUrl): string
    {
        $uri = new Uri($shopUrl);
        $uri = $uri->withPath(preg_replace('#/{2,}#', '/', $uri->getPath()));

        return (string)$uri;
    }
```

Comment (MoritzKrafeld) [reply src/Registration/RegistrationService.php:159]: I kept the sanitization of multiple slashes :smile:

**Review by fschmtt — APPROVED** [review]

**Review by nsaliu — APPROVED** [review]

**Review by adrianles — APPROVED** [review]

**Review by shyim — APPROVED** [review]
